spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tasklist_db?currentSchema=tasklist
    username: postgres
    password: mother1963
  sql:
    init:
      mode: never
      continue-on-error: false
 #     data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
  jwt:
    secret: bmRmYnZ2amZudmp2anZqdm12YmR4aHhoZ2dzY3NseHBjb2NpdWRjZ3N2c2J4Y21ja0hGSEZIQkNCRkJGSEhOQ05DTkNNQ0tY
    access: 3600000
    refresh: 2592000000
springdoc:
  override-with-generic-response: false